### ISSUE TITLE
Veil-Pillage Fails to Properly Use Proxy

### ISSUE THREAD

**Issue by burrowingsec** [Veil-Framework/Veil-Pillage#10]
I am attempting to force Pillage to send traffic through a proxy. I am attempting to deliver a payload to a host using Pillage's psexec-like functionality. My target host makes use of Trust Relationships and only allows SMB connections from systems within its domain.

To solve the trust issues I added a route with Metasploit and ran the auxiliary/server/socks4a module. I then ran Pillage with proxychains python Veil-Pillage.py. All of this looks fine and appears to work correctly until I actually "run" the Pillage module. I receive the error: 

`error: SMB SessionError: STATUS_TRUSTED_RELATIONSHIP_FAILURE(The logon request failed because the trust relationship between this workstation and the primary domain failed.)`

![image](https://cloud.githubusercontent.com/assets/12588870/7790176/8c862d3e-0275-11e5-9025-4c2b58480687.png)

I believe that this is an issue with Pillage as tools like keimpx are able to successfully connect and authenticate using the same credentials and proxy.

![image](https://cloud.githubusercontent.com/assets/12588870/7790203/938b2782-0276-11e5-8723-08930588f114.png)

![image](https://cloud.githubusercontent.com/assets/12588870/7790209/c25fcdf6-0276-11e5-8695-b2afb859fb1a.png)

Anything you could do to help troubleshoot this would be greatly appreciated.

Veil-Pillage version: 1.1.2
Python version: Python 2.7.3
Metasploit version: Framework: 4.11.2-2015051401 Console  : 4.11.2-2015051401.15168
Impacket version: 0.9.14

**Comment by ChrisTruncer** [comment]
Hi there,

I'm assuming this probably isn't an issue since this (unfortunately) wasn't looked at on our side in quite some time. I apologize, but thanks for submitting an issue.
