### ISSUE TITLE
credential query not comprehensive

### ISSUE THREAD

**Issue by caoimhinp** [Veil-Framework/Veil-Pillage#4]
Veil-Pillage does not return the credentials stored in my database.

My database also saves credentials to:
<code>
metasploit_credential_privates (id, type, data, created_at, updated_at, jtr_format) 
</code>

The query performed in msfdatabase.py only checks the creds table which isn't even populated in my current database.
The msfconsole commands <code>creds</code> and <code>loot</code> function normally.

Note this change in the current https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/console/command_dispatcher/db.rb

<code>
# cred_table_columns = [ 'host', 'port', 'user', 'pass', 'type', 'proof', 'active?' ]

cred_table_columns = [ 'host', 'service', 'public', 'private', 'realm', 'private_type' ]
</code>

I'll provide a patch if possible. I'm trying to figure out how metasploit does it's query ... and I hate ruby.

You'll note that there will be a couple joins necessary as metasploit_credential_privates table really only has one value and that's the "data" column. The "type" column specifies what type of value is in the "data" column i.e. ntlm hash or password. I assume some other tables reference the id for the credentials_privates table.

**Comment by ChrisTruncer** [comment]
lol, I hate ruby too.  Sorry this took so long to respond to, but I assume this is no longer an issue.  Thanks for reporting this at the time.

**Comment by caoimhinp** [comment]
Yeah, not an issue anymore. And I hate ruby less now :)

**Comment by ChrisTruncer** [comment]
:)
