### ISSUE TITLE
Error in "management/run_command" module

### ISSUE THREAD

**Issue by interference-security** [Veil-Framework/Veil-Pillage#7]
Specifying any command in using "set command" in "management/run_command" module shows an error message "Error: not all arguments converted during string formatting". Then saves & exits Veil-Pillage.
![image](https://cloud.githubusercontent.com/assets/5358495/5607022/268acdf6-946f-11e4-9568-d6a0886f79f6.png)

**Comment by HarmJ0y** [comment]
nice catch, should be fixed now. thanks!
