### ISSUE TITLE
Error in "management/enable_proxy" module

### ISSUE THREAD

**Issue by interference-security** [Veil-Framework/Veil-Pillage#8]
![image](https://cloud.githubusercontent.com/assets/5358495/5607035/774e38e0-946f-11e4-86c1-56ab8dafbd7e.png)

"management/enable_proxy" module shows an error message after proxy_url has been setup and module is executed.

![image](https://cloud.githubusercontent.com/assets/5358495/5607043/8b1e1e44-946f-11e4-80ef-80f05db99cdd.png)

**Comment by HarmJ0y** [comment]
Couldn't recreate, but made a tweak to hopefully fix it. Does the newest version fix the issue?

**Comment by interference-security** [comment]
Working fine now.
"git clone https://github.com/Veil-Framework/Veil.git" isn't getting the changes made in Veil-Pillage git repo.

**Comment by ChrisTruncer** [comment]
It should be fixed in Veil super project.  Let us know if it isn't!
