### ISSUE TITLE
credentials always fail

### ISSUE THREAD

**Issue by pairughdocks** [Veil-Framework/Veil-Pillage#9]
I just got Veil-Framework configured on my Kali X64 distro, I was working inside Veil-Pillage after watching your presentation at DEF CON 22 (very cool, by the way). I am testing some of the basic modules but not having much luck.

Host:
-Kali Linux X64
-192.168.1.157
-Veil-Pillage 1.1.2 (already ran update script)

Target:
-Windows 7 Pro X64
-192.168.1.131
-username: media
-password: 1234

So, I was attempting to do the following:

1. set targets 192.168.1.131
2. username: media (also tried media-pc\media)
3. password: 1234
4. use management/run_command
5. set command notepad.exe
6. run
7. I am always met with the following:
 Module: 	Run Command

 Output file:   /root/veil-output/pillage/run_command/04.11
                .2015.141028.out

 [*] Execution completed

 [>] Display the output file? [y/N] y

 [*] Output File:

	[*] Results for 'notepad' using creds 'media-pc\media:1234' on 192.168.1.131 : 
	error: credentials failed

No matter what I try for a username/password. I know those credentials are right, I just made the password 1234, and I can log in normally with it via RDP/Locally.

Any advice/suggestions? My laptop can access the SMB shares I have running off of that PC as well, so they CAN communicate just fine.

Looking forward to your response,
pairughdocks

**Comment by abdullsaeedi** [comment]
I have exactly the same problem, I searched everywhere for an answer, but no luck ! someone help us please :)

**Comment by ChrisTruncer** [comment]
Are you local admin on the box?

**Comment by ChrisTruncer** [comment]
Also, it's going to be worth reviewing this - http://www.harmj0y.net/blog/penetesting/pass-the-hash-is-dead-long-live-pass-the-hash/
